# infra/cloudbuild-frontend.yaml
# YAML-only pipeline: build from source (apps/web) with Cloud Run Buildpacks
# and deploy to Cloud Run. No Dockerfile is used.

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "asia-south1"
  _SERVICE: "manthan-frontend"
  # IMPORTANT: set this to your backend HTTPS base (NO trailing slash)
  _API_BASE: "https://manthan-backend-asia-south1.run.app"

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Build & Deploy (source)
    entrypoint: bash
    args:
      - -lc
      - |
        # Build from apps/web and deploy with envs.
        # NPM_CONFIG_PRODUCTION=false ensures devDeps available for Next build.
        gcloud run deploy ${_SERVICE} \
          --source ./apps/web \
          --region ${_REGION} \
          --allow-unauthenticated \
          --build-env-vars NPM_CONFIG_PRODUCTION=false \
          --set-env-vars API_BASE=${_API_BASE}

# NOTE: with --source deploys, Cloud Run stores the image in a managed repo
# (cloud-run-source-deploy). You don't need an explicit "images:" section.



