# infra/cloudbuild-frontend.yaml
# Builds the Next.js frontend (apps/web) with the Dockerfile and deploys to Cloud Run.

substitutions:
  _REGION: asia-south1
  _SERVICE: manthan-frontend
  _IMAGE: gcr.io/${PROJECT_ID}/manthan-frontend
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY   # <-- satisfies the service account + logs requirement

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${_TAG}
      - -f
      - apps/web/Dockerfile     # Dockerfile lives here
      - .                       # build context is the repo root

  # Optional: auto-deploy to Cloud Run after image build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}:${_TAG}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

images:
  - ${_IMAGE}:${_TAG}

# Optional: extend build time or machine
# timeout: "2400s"
# options:
#   machineType: "E2_HIGHCPU_8"
