# infra/cloudbuild-frontend.yaml
# Builds Next.js frontend with the Dockerfile above and deploys to Cloud Run.

substitutions:
  # set to your values or override in the trigger UI
  _LOCATION: "asia-south1"
  _REPO: "manthan"
  _SERVICE: "manthan-frontend"
  _NEXT_PUBLIC_API_BASE: "https://manthan-backend-asia-south1.run.app"

images:
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the image from repo ROOT, telling Docker where the Dockerfile lives.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - apps/web/Dockerfile
      - "-t"
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA
      - "-t"
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest
      - "--build-arg"
      - NEXT_PUBLIC_API_BASE=${_NEXT_PUBLIC_API_BASE}
      - "."
    dir: "."

  # Push (Cloud Build auto-pushes images listed under `images`, but this is explicit)
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - "--image"
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA
      - "--region"
      - ${_LOCATION}
      - "--platform"
      - managed
      - "--allow-unauthenticated"
      - "--port"
      - "8080"

