- name: gcr.io/cloud-builders/docker
  args: ["build","-t","${_IMAGE}:${_TAG}","-f","apps/web/Dockerfile","."]
- name: gcr.io/cloud-builders/docker
  args: ["push","${_IMAGE}:${_TAG}"]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ["run","deploy","${_SERVICE}","--image=${_IMAGE}:${_TAG}","--region=${_REGION}","--platform=managed","--allow-unauthenticated","--quiet"]
options:
  logging: CLOUD_LOGGING_ONLY



