# infra/cloudbuild-frontend.yaml
# Build & deploy the frontend from apps/web/Dockerfile via Artifact Registry.

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY

# User substitutions (no nested expansion here)
substitutions:
  _REGION: "asia-south1"
  _REPO: "manthan"            # Artifact Registry repo name (must exist in asia-south1)
  _SERVICE: "manthan-frontend"

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - -t
      - asia-south1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - asia-south1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - asia-south1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - asia-south1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}


