options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-south1
  _REPO: manthan-repo
  _SERVICE: manthan-backend

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -f
    - apps/api/Dockerfile
    - -t
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
    - apps/api

- name: gcr.io/cloud-builders/docker
  args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
    - --region=${_REGION}
    - --project=${PROJECT_ID}
    - --allow-unauthenticated
    - --set-env-vars=ALLOWED_ORIGIN=https://manthan-frontend-${_REGION}.run.app
    - --set-env-vars=MODEL_NAME=gpt-5
    - --set-env-vars=GCP_PROJECT_ID=${PROJECT_ID}
    - --set-env-vars=GCS_BUCKET=manthan-assets
    - --set-env-vars=FIRESTORE_NAMESPACE=prod
    - --set-env-vars=ENABLE_IMAGE_GEN=false
    - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
    - --cpu=1
    - --memory=512Mi



