# =========================
# Frontend (Next.js App Router)
# Monorepo path: apps/web
# Output: Cloud Run-ready distroless image
# =========================

# ---- 1) DEPS: install workspace deps with pnpm (faster, reproducible)
FROM node:20-bookworm-slim AS deps
WORKDIR /app
ENV NODE_ENV=development
# Ensure pnpm is available
RUN corepack enable

# Copy only manifests first for better layer caching
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/web/package.json apps/web/

# Install workspace dependencies (no build yet)
# We install at the root so workspaces are hoisted correctly.
RUN pnpm install --frozen-lockfile

# ---- 2) BUILD: copy full repo and build Next in standalone mode
FROM node:20-bookworm-slim AS builder
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable

# Bring in node_modules from deps stage
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=deps /app/apps/web/node_modules /app/apps/web/node_modules
COPY --from=deps /app/package.json /app/package.json
COPY --from=deps /app/apps/web/package.json /app/apps/web/package.json
COPY pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy the rest of the repository (source code, components, etc.)
COPY . .

# IMPORTANT: build only the web app (monorepo)
# This will produce .next/standalone, .next/static because next.config output=standalone
RUN pnpm -w build --filter ./apps/web

# ---- 3) RUNTIME: super small, secure image
FROM gcr.io/distroless/nodejs20-debian12 AS runner
WORKDIR /app
ENV NODE_ENV=production
# Cloud Run listens on PORT; Next's server.js uses process.env.PORT || 3000
ENV PORT=8080
EXPOSE 8080

# Copy the Next.js standalone server and static assets
# After the build, Next places a self-contained server at apps/web/.next/standalone
COPY --from=builder /app/apps/web/.next/standalone ./
# Static assets (required for _next/static/*)
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
# Public assets (e.g., /brand-wordmark-mos.svg)
COPY --from=builder /app/apps/web/public ./apps/web/public

# Start the Next standalone server (distroless already has node runtime)
CMD ["apps/web/server.js"]



