substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/manthan-frontend
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${_TAG}
      - -f
      - apps/web/Dockerfile
      - .

images:
  - ${_IMAGE}:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
