steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","$_IMAGE","-f","Dockerfile.frontend","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","$_IMAGE"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [ "run","deploy", ... ]
images:
  - $_IMAGE
options:
  logging: CLOUD_LOGGING_ONLY
