# infra/cloudbuild-frontend.yaml
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-south1
  _REPO: manthan-repo
  _SERVICE: manthan-frontend
  _API_BASE: https://manthan-backend-${_REGION}.run.app

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -f
    - apps/web/Dockerfile
    - -t
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
    - .

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}
    - --region=${_REGION}
    - --project=${PROJECT_ID}
    - --allow-unauthenticated
    - --set-env-vars=NEXT_PUBLIC_API_BASE=${_API_BASE}
    - --cpu=1
    - --memory=512Mi


